#if UNITY_EDITOR || DEVELOPMENT_BUILD
namespace AirTools.Dev
{
    /// Grok lane G2's example payloads, copied from the backend (integration/grok-all @ c706f13): its tests, its docs/api.md
    /// examples, and the running OFFLINE server (:8003). Used by the EditMode tests (GrokOverlayTests) and by
    /// AgentHarness.GrokCheck("g2"). Generated by the lane's scratch script; SYNTHETIC ones say so.
    public static class GrokG2Fixtures
    {
        /// show_plan: along_edge o10 every 200 mm on tests/fixtures/structure/kitchen (server/plan.py along_edge, as in test_agent_plan_placement_shows_the_plan_then_places_it: 3 points, 137 mm).
        public const string KitchenPlanHooks = @"{""plan_id"":""p-5e0c9a17"",""segments"":[{""a"":[-1.345,0.011,-0.673],""b"":[-1.303,0.011,-1.219],""length_m"":0.548}],""points"":[[-1.334,0.011,-0.81],[-1.324,0.011,-0.946],[-1.314,0.011,-1.083]],""label"":""Planned from the scan; check with the tape""}";

        /// place_array after "place them" on that plan (test_plan.py: {spacing_mm: 137, plan_id}).
        public const string KitchenPlaceHooks = @"{""spacing_mm"":137,""plan_id"":""p-5e0c9a17""}";

        /// show_plan: the LED run under the wall cabinets (docs/api.md POST /scene/plan response; points [] = a run).
        public const string KitchenPlanLed = @"{""plan_id"":""p-2ff2f84c"",""segments"":[{""a"":[-1.413,0.03,1.213],""b"":[-1.303,0.01,-1.219],""length_m"":2.433}],""points"":[],""label"":""Planned from the scan; check with the tape""}";

        /// show_plan: hangers every 600 mm along the fascia/gutter edge e101 of synthetic-facade's structure.r1.json (server/plan.py along_edge: 8 points, 557 mm).
        public const string FacadePlanFascia = @"{""plan_id"":""p-a41f3c06"",""segments"":[{""a"":[2.1,6.1,0.025],""b"":[-2.1,6.1,0.025],""length_m"":4.2}],""points"":[[1.95,6.1,0.025],[1.393,6.1,0.025],[0.836,6.1,0.025],[0.279,6.1,0.025],[-0.279,6.1,0.025],[-0.836,6.1,0.025],[-1.393,6.1,0.025],[-1.95,6.1,0.025]],""label"":""Planned from the scan; check with the tape""}";

        /// place_array after "place them" on the fascia plan.
        public const string FacadePlaceFascia = @"{""spacing_mm"":557,""plan_id"":""p-a41f3c06""}";

        /// survey_started from "survey the roof" on tests/fixtures/survey/kitchen (test_agent_survey_then_fix_pin, REPLY mocked).
        public const string KitchenSurveyStarted = @"{""survey_id"":""51815765bd49""}";

        /// show_survey in the same reply (2 pins: f1 severe gutter, f2 minor suspected hail).
        public const string KitchenShowSurvey = @"{""survey_id"":""51815765bd49"",""pins"":[{""frame_id"":""0001"",""box"":[0.4,0.4,0.6,0.6],""element"":""gutter"",""severity"":""severe"",""confidence"":0.9,""issue"":""Gutter sagging, joint split"",""action"":""replace"",""part_query"":""5 in aluminium K-style gutter section"",""suspected"":false,""p"":[-1.4456,-0.3977,-0.9531],""also_in"":[""0001""],""id"":""f1""},{""frame_id"":""0701"",""box"":[0.4,0.4,0.6,0.6],""element"":""roof_covering"",""severity"":""minor"",""confidence"":0.8,""issue"":""Possible hail impact marks (suspected, verify on the roof)"",""action"":""inspect_closer"",""part_query"":null,""suspected"":true,""p"":[-1.3846,0.2529,0.5101],""also_in"":[],""id"":""f2""}],""label"":""AI triage from drone frames, not an inspection""}";

        /// GET /scene/survey/{id} for that survey (status done).
        public const string KitchenSurveyBody = @"{""survey_id"":""51815765bd49"",""status"":""done"",""site"":""kitchen"",""rev"":1,""model"":""xai:grok-4.20-0309-non-reasoning"",""frames"":[{""id"":""0701"",""file"":""thumbs/0701.jpg""},{""id"":""0001"",""file"":""thumbs/0001.jpg""}],""pins"":[{""frame_id"":""0001"",""box"":[0.4,0.4,0.6,0.6],""element"":""gutter"",""severity"":""severe"",""confidence"":0.9,""issue"":""Gutter sagging, joint split"",""action"":""replace"",""part_query"":""5 in aluminium K-style gutter section"",""suspected"":false,""p"":[-1.4456,-0.3977,-0.9531],""also_in"":[""0001""],""id"":""f1""},{""frame_id"":""0701"",""box"":[0.4,0.4,0.6,0.6],""element"":""roof_covering"",""severity"":""minor"",""confidence"":0.8,""issue"":""Possible hail impact marks (suspected, verify on the roof)"",""action"":""inspect_closer"",""part_query"":null,""suspected"":true,""p"":[-1.3846,0.2529,0.5101],""also_in"":[],""id"":""f2""}],""looked_fine"":[""window (0701)""],""coverage_gaps"":[""Downspouts are out of frame""],""spoken"":""2 problems found, 2 pinned. Worst is the gutter, severe: Gutter sagging, joint split."",""label"":""AI triage from drone frames, not an inspection"",""cached"":false,""cost_usd"":0.0071,""latency_s"":0.0}";

        /// GET /scenes/kitchen/coverage from the running server (interior: no ring, a note).
        public const string KitchenCoverage = @"{""site"":""kitchen"",""rev"":1,""cameras"":""cameras.r1.json"",""registered"":165,""units"":""m"",""target"":{""centre"":[-1.2267995487587007,-1.173244276077415,0.006085258462160792],""width"":2.5819935266760217,""height"":1.8201233641847434},""mode"":""interior"",""verdict"":""not_applicable"",""legs"":[],""note"":""This scan is only 3 metres across, so it looks like a room or an object. The capture coach only plans drone flights around a building."",""spoken"":""This scan is only 3 metres across, so it looks like a room or an object. The capture coach only plans drone flights around a building."",""spoken_source"":""template""}";

        /// GET /scenes/synthetic-facade/coverage from the running server (exterior: 2 of 8 sides, 2 orbits + a nadir grid).
        public const string FacadeCoverage = @"{""site"":""synthetic-facade"",""rev"":1,""cameras"":""cameras.r1.json"",""registered"":12,""units"":""m"",""target"":{""centre"":[-0.004076240863114755,-0.05000000074505806,2.5127783282474896],""width"":34.88230709254618,""height"":5.099249782878173},""mode"":""exterior"",""zero"":""start_side"",""ring"":{""centre"":[-0.004076240863114755,-0.05000000074505806,2.5127783282474896],""radius"":19.1852689009004,""zero_dir"":[0.9673965914499472,0.0,0.25326633185448094],""quarter_dir"":[-0.25326633185448094,0.0,0.9673965914499472]},""sides"":[{""label"":""front"",""bearing_deg"":0.0,""views"":2.0,""seen"":false},{""label"":""front-left"",""bearing_deg"":45.0,""views"":4.0,""seen"":true},{""label"":""left"",""bearing_deg"":90.0,""views"":2.0,""seen"":false},{""label"":""back-left"",""bearing_deg"":135.0,""views"":4.0,""seen"":true},{""label"":""back"",""bearing_deg"":180.0,""views"":0.0,""seen"":false},{""label"":""back-right"",""bearing_deg"":225.0,""views"":0.0,""seen"":false},{""label"":""right"",""bearing_deg"":270.0,""views"":0.0,""seen"":false},{""label"":""front-right"",""bearing_deg"":315.0,""views"":0.0,""seen"":false}],""seen"":2,""aimed"":12,""pitch"":{""nadir"":0,""oblique"":0,""level"":12},""legs"":[{""pattern"":""orbit"",""from_deg"":67.5,""sweep_deg"":45.0,""sides"":[2],""gimbal_pitch_deg"":30,""radius"":34.88230709254618,""altitude"":22.68893428127581,""radius_widths"":1.0,""altitude_widths"":0.65},{""pattern"":""orbit"",""from_deg"":157.5,""sweep_deg"":225.0,""sides"":[4,5,6,7,0],""gimbal_pitch_deg"":30,""radius"":34.88230709254618,""altitude"":22.68893428127581,""radius_widths"":1.0,""altitude_widths"":0.65},{""pattern"":""nadir_grid"",""from_deg"":null,""sweep_deg"":null,""sides"":[],""gimbal_pitch_deg"":90,""radius"":17.44115354627309,""altitude"":39.98155687542435,""radius_widths"":0.5,""altitude_widths"":1.15}],""verdict"":""reshoot_most"",""spoken"":""You've covered 2 of 8 sides (front-left, back-left). Next, orbit on the left side, 35 m out from the middle and 25 m up, camera 30 degrees down; then orbit from the back round to the front, 35 m out from the middle and 25 m up, camera 30 degrees down; then a straight-down grid over the roof, 40 m up."",""spoken_source"":""template""}";

        /// show_labels on kitchen frame 0221 (tests/fixtures/labels/grok_0221_electrical.ndjson through server/labels.py normalise).
        public const string KitchenLabels = @"{""frame_id"":""0221"",""labels"":[{""name"":""electrical outlet"",""kind"":""outlet"",""detail"":""white duplex receptacle"",""source"":""seen"",""box"":[0.125,0.29,0.182,0.385],""confidence"":0.9,""query"":""white duplex receptacle electrical outlet"",""id"":""l0""},{""name"":""light switch"",""kind"":""switch"",""detail"":""white single-pole toggle"",""source"":""seen"",""box"":[0.2,0.285,0.255,0.38],""confidence"":0.85,""query"":""white single-pole toggle light switch"",""id"":""l1""},{""name"":""stainless steel sink"",""kind"":""sink"",""detail"":""undermount single basin"",""source"":""seen"",""box"":[0.2,0.57,0.65,0.75],""confidence"":0.95,""query"":""undermount single basin stainless steel sink"",""id"":""l2""},{""name"":""chrome faucet"",""kind"":""faucet"",""detail"":""single-handle gooseneck"",""source"":""seen"",""box"":[0.39,0.39,0.495,0.53],""confidence"":0.9,""query"":""single-handle gooseneck chrome faucet"",""id"":""l3""},{""name"":""warning sign"",""kind"":""other"",""detail"":""red rectangular safety notice"",""source"":""printed_text"",""box"":[0.335,0.25,0.49,0.365],""confidence"":0.95,""query"":""red rectangular safety notice warning sign"",""id"":""l4""},{""name"":""wood cabinet"",""kind"":""cabinet"",""detail"":""light brown upper cabinet"",""source"":""seen"",""box"":[0.0,0.0,0.23,0.085],""confidence"":0.8,""query"":""light brown upper cabinet wood cabinet"",""id"":""l5""}]}";

        /// GET /scenes/kitchen/labels (docs/api.md example; the running server has none warmed: 404).
        public const string KitchenSceneLabels = @"{""site"":""kitchen"",""rev"":1,""frames"":42,""unpinned"":0,""cost_usd"":0.058,""label"":""Grok's reading of the camera view. Sizes are shown only when printed on the part."",""labels"":[{""id"":""a18"",""name"":""outlet"",""kind"":""outlet"",""detail"":""white duplex"",""source"":""seen"",""confidence"":0.8,""query"":""white duplex outlet"",""pos"":[-1.58,-0.38,0.39],""frames"":[""0221"",""0201"",""0241"",""0181""]}]}";

        /// SYNTHETIC show_survey for the facade (the backend has no facade survey): a severe gutter pin, a moderate fascia pin, a minor pin with no point.
        public const string FacadeSurvey = @"{""survey_id"":""synthetic-facade-g2"",""pins"":[{""id"":""f1"",""p"":[1.2,6.04,0.152],""frame_id"":""0002"",""box"":[0.3,0.1,0.5,0.2],""element"":""gutter"",""severity"":""severe"",""confidence"":0.9,""issue"":""Gutter sagging, joint split"",""action"":""replace"",""part_query"":""5 in aluminium K-style gutter section"",""suspected"":false,""also_in"":[]},{""id"":""f2"",""p"":[-1.0,6.15,0.025],""frame_id"":""0008"",""box"":[0.5,0.1,0.7,0.2],""element"":""fascia"",""severity"":""moderate"",""confidence"":0.7,""issue"":""Fascia paint peeling"",""action"":""repair"",""part_query"":""exterior wood filler"",""suspected"":false,""also_in"":[]},{""id"":""f3"",""p"":null,""frame_id"":""0005"",""box"":[0.1,0.1,0.2,0.2],""element"":""roof_covering"",""severity"":""minor"",""confidence"":0.6,""issue"":""Possible hail impact marks (suspected, verify on the roof)"",""action"":""inspect_closer"",""part_query"":null,""suspected"":true,""also_in"":[]}],""label"":""AI triage from drone frames, not an inspection""}";

        /// SYNTHETIC show_labels on synthetic-facade frame 0005: boxes are the structure's window o0 and door o1 projected into that camera.
        public const string FacadeLabels = @"{""frame_id"":""0005"",""labels"":[{""id"":""l0"",""name"":""window"",""kind"":""window"",""detail"":""size not visible"",""source"":""seen"",""box"":[0.432,0.323,0.569,0.47],""confidence"":0.9,""query"":""window""},{""id"":""l1"",""name"":""door"",""kind"":""door"",""detail"":""size not visible"",""source"":""seen"",""box"":[0.199,0.649,0.287,0.907],""confidence"":0.65,""query"":""exterior door""}]}";

        public const string KitchenSurveyReply = @"2 problems found, 2 pinned. Worst is the gutter, severe: Gutter sagging, joint split.";
        public const string KitchenLabelsReply = @"I see the electrical outlet, the light switch and the stainless steel sink. Tap one to shop for it.";
        public const string KitchenPlanHooksReply = @"Three along 0.55 metres, 137 millimetres apart.";
        public const string KitchenPlanLedReply = @"One run under the wall cabinets, 2.43 metres. Three 1-metre strips, cut the last.";

        /// synthetic-facade's 12 camera centres (cameras.r1.json `position`, glTF frame): the flight's side of the ring.
        public static readonly double[][] FacadeCameraPositions =
        {
            new[] { 5.734065, 1.5, 4.015035 },
            new[] { 4.949748, 2.05, 4.949748 },
            new[] { 4.015035, 2.6, 5.734065 },
            new[] { 2.958328, 1.5, 6.344154 },
            new[] { 1.811733, 2.05, 6.761481 },
            new[] { 0.61009, 2.6, 6.973363 },
            new[] { -0.61009, 1.5, 6.973363 },
            new[] { -1.811733, 2.05, 6.761481 },
            new[] { -2.958328, 2.6, 6.344154 },
            new[] { -4.015035, 1.5, 5.734065 },
            new[] { -4.949748, 2.05, 4.949747 },
            new[] { -5.734065, 2.6, 4.015035 },
        };

        /// kitchen camera 0221 (cameras.r1.json): the frame the labels fixture was read from.
        public const string KitchenCamera0221 = @"{""id"":""0221"",""file"":""frames/0221.jpg"",""thumb"":""thumbs/0221.jpg"",""R"":[[-0.027314338977018796,-0.00035603174624644564,-0.9996268304360603],[0.2355259463881509,-0.9718489834236435,-0.006089498862508089],[-0.9714841509073703,-0.23560438590957147,0.026629267281683446]],""t"":[-0.11333819672284384,-0.14406606565269248,-0.6732169363703029],""position"":[-0.6231840452752287,-0.29866367432395696,-0.09624591876315228],""fx"":1457.6137201326615,""fy"":1457.6137201326615,""cx"":960.0,""cy"":539.5,""w"":1920,""h"":1079}";
    }
}
#endif
